name: assigning a pull request


on:
 pull_request:
   types: opened


permissions: 
  pull-requests: write


jobs:
  pr_assignment:
    runs-on: ubuntu-latest

    steps:
      - name: pull request assignment
        run: gh pr edit ${{ github.event.pull_request.number }} --add-assignee sakaraynikhil
      
  
