name: pull request validation


on:
  pull_request:
    types:
      - opened
      - synchronize


jobs:
  pr-validation:
    runs-on: ubuntu-latest

    steps:
      - name: pr is validating
        run: echo "pr is getting validated"

      - name: pr validation is success
        run: echo "pr is successfully validated"
